setwd("C:/Users/nupur/OneDrive/Documents/Data Mining/use case study")
train_data<-read.csv("train_u6lujuX_CVtuZ9i_p.csv")
boxplot(train_data$LoanAmount,main="Boxplot of Original LoanAmount")
summary(train_data$LoanAmount)
hist(train_data$LoanAmount)
train_data$LoanAmount[is.na(train_data$LoanAmount)] <- 328
View(train_data$LoanAmount)
hist(train_data$LoanAmount)
boxplot(train_data$LoanAmount,main="Boxplot of Cleaned LoanAmount")
summary(train_data$LoanAmount)
View(which.max(train_data$LoanAmount))
View(train_data[172,])
View(which.max(train_data$ApplicantIncome))
View(train_data[410,])
View(train_data[c(172,410),])
boxplot(train_data$ApplicantIncome,main="Boxplot of Cleaned LoanAmount")
boxplot(train_data$CoapplicantIncome)
boxplot(train_data$ApplicantIncome)
hist(train_data)
hist(train_data$ApplicantIncome,main="Histogram of Cleaned ApplicantIncome")
train_data
train_data<-train_data[!train_data$ApplicantIncome>20000,]
hist(train_data$ApplicantIncome)
which.min(train_data$CoapplicantIncome)
View(which.min(train_data$CoapplicantIncome))
View(train_data[1,])
hist(train_data$CoapplicantIncome)
train_data<-train_data[!train_data$CoapplicantIncome>10000,]
hist(train_data$CoapplicantIncome,main="Histogram of Cleaned CoapplicantIncome")
hist(train_data$LoanAmount,main="Histogram of Cleaned LoanAmount")
View(train_data)
write.csv(train_data, "training_data_cleaned.csv")
